
package gossip.stat.client.soap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StatServerService", targetNamespace = "http://server.stat.gossip/", wsdlLocation = "http://localhost:8000/gossip?wsdl")
public class StatServerService
    extends Service
{

    private final static URL STATSERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gossip.stat.client.soap.StatServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gossip.stat.client.soap.StatServerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8000/gossip?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8000/gossip?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STATSERVERSERVICE_WSDL_LOCATION = url;
    }

    public StatServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatServerService() {
        super(STATSERVERSERVICE_WSDL_LOCATION, new QName("http://server.stat.gossip/", "StatServerService"));
    }

    /**
     * 
     * @return
     *     returns StatServer
     */
    @WebEndpoint(name = "StatServerPort")
    public StatServer getStatServerPort() {
        return super.getPort(new QName("http://server.stat.gossip/", "StatServerPort"), StatServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatServer
     */
    @WebEndpoint(name = "StatServerPort")
    public StatServer getStatServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.stat.gossip/", "StatServerPort"), StatServer.class, features);
    }

}
